import json
from pathlib import Path

# Combined semantic extraction result from all 3 subagents.
combined = {
  "nodes": [
    # === Chunk 1: Docs ===
    {"id":"readme_dotween","label":"DOTween Readme","file_type":"document","source_file":"Assets/Plugins/Demigiant/DOTween/readme.txt","source_location":None,"source_url":None,"captured_at":None,"author":"Daniele Giardini (Demigiant)","contributor":None},
    {"id":"project_architecture","label":"Project Architecture Documentation","file_type":"document","source_file":"Assets/Project/Documentation/PROJECT_ARCHITECTURE.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"liberationsans_ofl","label":"Liberation Sans Font License (OFL)","file_type":"document","source_file":"Assets/TextMesh Pro/Fonts/LiberationSans - OFL.txt","source_location":None,"source_url":None,"captured_at":None,"author":"Red Hat / Google (Arimo, Tinos, Cousine)","contributor":None},
    {"id":"linebreaking_following","label":"TextMesh Pro Line-Breaking Following Characters","file_type":"document","source_file":"Assets/TextMesh Pro/Resources/LineBreaking Following Characters.txt","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"linebreaking_leading","label":"TextMesh Pro Line-Breaking Leading Characters","file_type":"document","source_file":"Assets/TextMesh Pro/Resources/LineBreaking Leading Characters.txt","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"emojione_attribution","label":"EmojiOne Attribution","file_type":"document","source_file":"Assets/TextMesh Pro/Sprites/EmojiOne Attribution.txt","source_location":None,"source_url":None,"captured_at":None,"author":"EmojiOne","contributor":None},
    {"id":"backlog_md","label":"Engineering Backlog","file_type":"document","source_file":"BACKLOG.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"project_roadmap","label":"Project Master Roadmap","file_type":"document","source_file":"PROJECT_ROADMAP.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"project_structure","label":"Project Folder Structure","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"readme_md","label":"Multi-Mode Card Framework README","file_type":"document","source_file":"README.md","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_blackjack_engine","label":"Blackjack Engine","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/Core/Engines/BlackjackEngine.cs","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_solitaire_engine","label":"Solitaire Engine","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/Core/Engines/SolitaireEngine.cs","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_texas_holdem_engine","label":"Texas Hold'em Engine (Future)","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/Core/Engines/TexasHoldemEngine.cs","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_di_container","label":"Dependency Injection Container","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/DependencyInjection/DependencyContainer.cs","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_fisher_yates","label":"Fisher-Yates Shuffle Algorithm","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/Core/Utils/ShuffleAlgorithm.cs","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_lootlocker_integration","label":"LootLocker Cloud Backend Integration","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/Cloud/","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_playfab_integration","label":"PlayFab Cloud Backend Integration","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/Cloud/PlayFab","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_xr_meta_quest","label":"Meta Quest 3 XR Integration","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/XR/","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_dotween_animation","label":"DOTween Tweening Library","file_type":"document","source_file":"BACKLOG.md","source_location":"Scripts/Presentation/CardView.cs","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_mvc_pattern","label":"Model-View-Controller (MVC) Architectural Pattern","file_type":"document","source_file":"README.md","source_location":"Architecture Section","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_assembly_definitions","label":"Assembly Definitions (AsmDef) Layering","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Key Improvements Section","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"concept_adaptive_ui","label":"Adaptive UI (Screen-Space vs World-Space)","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/Presentation/UI/AdaptiveUIManager.cs","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"rationale_xr_optional_assembly","label":"Rationale: XR as Optional Assembly","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Key Improvements Section #2","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"rationale_layer_organization","label":"Rationale: Scripts Organized by Layer Not Feature","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Key Improvements Section #3","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"rationale_input_separation","label":"Rationale: Input as Separate Assembly","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Key Improvements Section #4","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"rationale_asmdef_critical","label":"Rationale: Assembly Definitions Critical","file_type":"document","source_file":"PROJECT_STRUCTURE.md","source_location":"Key Improvements Section #1","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"epic_01_core_engine","label":"EPIC-01: Core Logic Engine","file_type":"document","source_file":"BACKLOG.md","source_location":"EPIC-01 Section","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"epic_02_cloud_backend","label":"EPIC-02: Persistence & Cloud Backend","file_type":"document","source_file":"BACKLOG.md","source_location":"EPIC-02 Section","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"epic_03_architecture_ui","label":"EPIC-03: Architecture & UI Foundation","file_type":"document","source_file":"BACKLOG.md","source_location":"EPIC-03 Section","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"epic_04_visual_presentation","label":"EPIC-04: 3D Visual Presentation","file_type":"document","source_file":"BACKLOG.md","source_location":"EPIC-04 Section","source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"epic_05_xr_monetization","label":"EPIC-05: XR Integration & Monetization","file_type":"document","source_file":"BACKLOG.md","source_location":"EPIC-05 Section","source_url":None,"captured_at":None,"author":None,"contributor":None},
    # === Chunk 2: Images (PlayFab Editor UI part 1) ===
    {"id":"playfab_editor_ui_asset_skin","label":"PlayFab Editor UI Asset Skin","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"azure_playfab_logo_brand_asset","label":"Azure PlayFab Logo (brand asset)","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/azure-playfab-logo.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"checkmark_toggle_button_states","label":"Checkbox/Toggle Button States (on/off/hover)","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dashboard_navigation_icon_states","label":"Dashboard Navigation Icon (default/hover)","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"gray_color_swatch_palette","label":"Gray Color Swatch Palette","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"clear_and_border_utility_textures","label":"Clear/Black and Border Utility Textures","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    # === Chunk 3: Images (PlayFab Editor UI part 2 + DOTween + EmojiOne) ===
    {"id":"playfab_logo_brand","label":"PlayFab Logo (Brand Asset)","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/playfablogo.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"playfab_logo_full_orange","label":"PlayFab Full Logo (Orange variant)","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/pfFullLogo_O.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"playfab_logo_full_white","label":"PlayFab Full Logo (White variant)","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/pfFullLogo_W.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"playfab_shared_logo","label":"PlayFab Logo (SDK Shared)","file_type":"image","source_file":"Assets/PlayFabSDK/Shared/Editor/PlayFablogo.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"playfab_rating_colored","label":"PlayFab Rating Icon (Colored)","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/r_colored.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"playfab_rating_gray","label":"PlayFab Rating Icon (Gray)","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/r_gray.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"playfab_textfield_hover","label":"PlayFab TextField Hover State","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/TextFieldHover.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"playfab_underline","label":"PlayFab Underline UI Element","file_type":"image","source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/underlineimg.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dotween_plugin_ui_asset","label":"DOTween Plugin UI Asset Set","file_type":"image","source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dotween_icon","label":"DOTween Plugin Icon","file_type":"image","source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenIcon.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dotween_mini_icon","label":"DOTween Mini Icon","file_type":"image","source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenMiniIcon.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dotween_footer","label":"DOTween Editor Footer (Light)","file_type":"image","source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dotween_footer_dark","label":"DOTween Editor Footer (Dark)","file_type":"image","source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer_dark.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"dotween_header","label":"DOTween Editor Header","file_type":"image","source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Header.jpg","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
    {"id":"emojione_sprite_atlas","label":"EmojiOne Sprite Atlas (TextMesh Pro)","file_type":"image","source_file":"Assets/TextMesh Pro/Sprites/EmojiOne.png","source_location":None,"source_url":None,"captured_at":None,"author":None,"contributor":None},
  ],
  "edges": [
    # Chunk 1 edges
    {"source":"concept_dotween_animation","target":"readme_dotween","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"BACKLOG.md","source_location":"TASK-4.2 references","weight":1.0},
    {"source":"concept_di_container","target":"readme_md","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"README.md","source_location":"Architecture Section","weight":1.0},
    {"source":"concept_mvc_pattern","target":"readme_md","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"README.md","source_location":"Key Design Patterns Table","weight":1.0},
    {"source":"concept_assembly_definitions","target":"project_structure","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_STRUCTURE.md","source_location":"Key Improvements #1","weight":1.0},
    {"source":"project_architecture","target":"project_structure","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/Project/Documentation/PROJECT_ARCHITECTURE.md","source_location":None,"weight":1.0},
    {"source":"concept_blackjack_engine","target":"epic_01_core_engine","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/Core/Engines/BlackjackEngine.cs","weight":1.0},
    {"source":"concept_solitaire_engine","target":"epic_01_core_engine","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/Core/Engines/SolitaireEngine.cs","weight":1.0},
    {"source":"concept_fisher_yates","target":"epic_01_core_engine","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/Core/Utils/ShuffleAlgorithm.cs","weight":1.0},
    {"source":"concept_lootlocker_integration","target":"epic_02_cloud_backend","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/Cloud/LootLocker/","weight":1.0},
    {"source":"concept_xr_meta_quest","target":"epic_05_xr_monetization","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_STRUCTURE.md","source_location":"Scripts/XR/","weight":1.0},
    {"source":"concept_adaptive_ui","target":"epic_03_architecture_ui","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_STRUCTURE.md","source_location":"AdaptiveUIManager.cs","weight":1.0},
    {"source":"concept_dotween_animation","target":"epic_04_visual_presentation","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"BACKLOG.md","source_location":"TASK-4.2","weight":1.0},
    {"source":"rationale_xr_optional_assembly","target":"concept_xr_meta_quest","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_STRUCTURE.md","source_location":"Key Improvements #2 Why","weight":1.0},
    {"source":"rationale_xr_optional_assembly","target":"concept_assembly_definitions","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_STRUCTURE.md","source_location":"Key Improvements #2","weight":1.0},
    {"source":"rationale_layer_organization","target":"concept_mvc_pattern","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_STRUCTURE.md","source_location":"Key Improvements #3 Why","weight":1.0},
    {"source":"rationale_input_separation","target":"concept_adaptive_ui","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_STRUCTURE.md","source_location":"Key Improvements #4 Why","weight":1.0},
    {"source":"rationale_asmdef_critical","target":"concept_assembly_definitions","relation":"rationale_for","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_STRUCTURE.md","source_location":"Key Improvements #1 Why","weight":1.0},
    {"source":"concept_di_container","target":"concept_mvc_pattern","relation":"conceptually_related_to","confidence":"INFERRED","confidence_score":0.85,"source_file":"README.md","source_location":"MVC Pattern uses DI","weight":0.85},
    {"source":"concept_playfab_integration","target":"concept_lootlocker_integration","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.85,"source_file":"README.md","source_location":"Backend Services Section","weight":0.85},
    {"source":"concept_blackjack_engine","target":"concept_solitaire_engine","relation":"shares_data_with","confidence":"INFERRED","confidence_score":0.7,"source_file":"PROJECT_STRUCTURE.md","source_location":"Both implement IGameEngine using CardData/Deck","weight":0.7},
    {"source":"concept_texas_holdem_engine","target":"concept_blackjack_engine","relation":"shares_data_with","confidence":"INFERRED","confidence_score":0.7,"source_file":"PROJECT_STRUCTURE.md","source_location":"Both in Core/Engines/ as pure C# engines","weight":0.7},
    {"source":"linebreaking_following","target":"linebreaking_leading","relation":"shares_data_with","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/TextMesh Pro/Resources/","source_location":"LineBreaking configuration pair","weight":1.0},
    {"source":"emojione_attribution","target":"liberationsans_ofl","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.75,"source_file":"Assets/TextMesh Pro","source_location":"Both are font/asset licensing attributions for TextMesh Pro","weight":0.75},
    {"source":"project_roadmap","target":"backlog_md","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_ROADMAP.md","source_location":"Updated roadmap corresponds to BACKLOG tasks","weight":1.0},
    {"source":"project_roadmap","target":"readme_md","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_ROADMAP.md","source_location":"Same author, project identity","weight":1.0},
    {"source":"concept_playfab_integration","target":"epic_02_cloud_backend","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"PROJECT_ROADMAP.md","source_location":"EPIC-2 Persistence & Cloud Backend","weight":1.0},
    {"source":"concept_di_container","target":"epic_03_architecture_ui","relation":"conceptually_related_to","confidence":"INFERRED","confidence_score":0.9,"source_file":"PROJECT_ROADMAP.md","source_location":"TASK-2.1 (VContainer setup in roadmap)","weight":0.9},
    {"source":"epic_01_core_engine","target":"epic_02_cloud_backend","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"BACKLOG.md","source_location":"Dependency Graph Section","weight":1.0},
    {"source":"epic_02_cloud_backend","target":"epic_03_architecture_ui","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"BACKLOG.md","source_location":"Dependency Graph Section","weight":1.0},
    {"source":"epic_03_architecture_ui","target":"epic_04_visual_presentation","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"BACKLOG.md","source_location":"Dependency Graph Section","weight":1.0},
    {"source":"epic_04_visual_presentation","target":"epic_05_xr_monetization","relation":"conceptually_related_to","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"BACKLOG.md","source_location":"Dependency Graph Section","weight":1.0},
    # Chunk 2 edges
    {"source":"azure_playfab_logo_brand_asset","target":"playfab_editor_ui_asset_skin","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/azure-playfab-logo.png","source_location":None,"weight":1.0},
    {"source":"checkmark_toggle_button_states","target":"playfab_editor_ui_asset_skin","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/checkmark_on.png","source_location":None,"weight":1.0},
    {"source":"dashboard_navigation_icon_states","target":"playfab_editor_ui_asset_skin","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/dashboardIcon.png","source_location":None,"weight":1.0},
    {"source":"gray_color_swatch_palette","target":"playfab_editor_ui_asset_skin","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/Gray_base.png","source_location":None,"weight":1.0},
    {"source":"clear_and_border_utility_textures","target":"playfab_editor_ui_asset_skin","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images/Clear.png","source_location":None,"weight":1.0},
    {"source":"azure_playfab_logo_brand_asset","target":"checkmark_toggle_button_states","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.2,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"weight":0.2},
    # Chunk 3 edges
    {"source":"playfab_logo_brand","target":"playfab_editor_ui_asset_skin","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"weight":1.0},
    {"source":"playfab_logo_full_orange","target":"playfab_editor_ui_asset_skin","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"weight":1.0},
    {"source":"playfab_logo_full_white","target":"playfab_editor_ui_asset_skin","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"weight":1.0},
    {"source":"playfab_rating_colored","target":"playfab_editor_ui_asset_skin","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"weight":1.0},
    {"source":"playfab_rating_gray","target":"playfab_editor_ui_asset_skin","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"weight":1.0},
    {"source":"playfab_textfield_hover","target":"playfab_editor_ui_asset_skin","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"weight":1.0},
    {"source":"playfab_underline","target":"playfab_editor_ui_asset_skin","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"weight":1.0},
    {"source":"playfab_shared_logo","target":"playfab_logo_brand","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.9,"source_file":"Assets/PlayFabSDK/Shared/Editor/PlayFablogo.png","source_location":None,"weight":0.9},
    {"source":"playfab_logo_full_orange","target":"playfab_logo_brand","relation":"conceptually_related_to","confidence":"INFERRED","confidence_score":0.85,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"weight":0.85},
    {"source":"playfab_logo_full_white","target":"playfab_logo_brand","relation":"conceptually_related_to","confidence":"INFERRED","confidence_score":0.85,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"weight":0.85},
    {"source":"playfab_rating_colored","target":"playfab_rating_gray","relation":"conceptually_related_to","confidence":"INFERRED","confidence_score":0.95,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images","source_location":None,"weight":0.95},
    {"source":"dotween_icon","target":"dotween_plugin_ui_asset","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs","source_location":None,"weight":1.0},
    {"source":"dotween_mini_icon","target":"dotween_plugin_ui_asset","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs","source_location":None,"weight":1.0},
    {"source":"dotween_footer","target":"dotween_plugin_ui_asset","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs","source_location":None,"weight":1.0},
    {"source":"dotween_footer_dark","target":"dotween_plugin_ui_asset","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs","source_location":None,"weight":1.0},
    {"source":"dotween_header","target":"dotween_plugin_ui_asset","relation":"references","confidence":"EXTRACTED","confidence_score":1.0,"source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs","source_location":None,"weight":1.0},
    {"source":"dotween_mini_icon","target":"dotween_icon","relation":"semantically_similar_to","confidence":"INFERRED","confidence_score":0.85,"source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs","source_location":None,"weight":0.85},
    {"source":"dotween_footer","target":"dotween_footer_dark","relation":"conceptually_related_to","confidence":"INFERRED","confidence_score":0.95,"source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs","source_location":None,"weight":0.95},
  ],
  "hyperedges": [
    {"id":"epic_01_dependency_chain","label":"EPIC-01 Critical Path (Core Engine Dependencies)","nodes":["epic_01_core_engine","concept_blackjack_engine","concept_solitaire_engine","concept_fisher_yates","concept_di_container"],"relation":"participate_in","confidence":"EXTRACTED","confidence_score":0.95,"source_file":"BACKLOG.md"},
    {"id":"cross_platform_backend_abstraction","label":"Cross-Platform Cloud Backend Abstraction","nodes":["concept_lootlocker_integration","concept_playfab_integration","concept_di_container","epic_02_cloud_backend"],"relation":"form","confidence":"INFERRED","confidence_score":0.85,"source_file":"README.md"},
    {"id":"assembly_definition_layering","label":"Assembly Definition Layering Architecture","nodes":["concept_assembly_definitions","rationale_asmdef_critical","rationale_xr_optional_assembly","concept_mvc_pattern","concept_di_container"],"relation":"form","confidence":"INFERRED","confidence_score":0.9,"source_file":"PROJECT_STRUCTURE.md"},
    {"id":"playfab_editor_button_state_patterns","label":"Button/Navigation UI State Variants (on/off/hover/default)","nodes":["checkmark_toggle_button_states","dashboard_navigation_icon_states"],"relation":"participate_in","confidence":"INFERRED","confidence_score":0.85,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images"},
    {"id":"playfab_branding_set","label":"PlayFab Brand Asset Variants","nodes":["playfab_logo_brand","playfab_logo_full_orange","playfab_logo_full_white","playfab_shared_logo"],"relation":"form","confidence":"INFERRED","confidence_score":0.9,"source_file":"Assets/PlayFabEditorExtensions/Editor/UI/Images"},
    {"id":"dotween_editor_chrome","label":"DOTween Editor Window Chrome","nodes":["dotween_header","dotween_footer","dotween_footer_dark","dotween_icon"],"relation":"form","confidence":"INFERRED","confidence_score":0.85,"source_file":"Assets/Plugins/Demigiant/DOTween/Editor/Imgs"},
    {"id":"unity_editor_textmesh_sprite_atlas","label":"Unity Editor / TextMesh Pro Sprite Asset","nodes":["emojione_sprite_atlas"],"relation":"participate_in","confidence":"INFERRED","confidence_score":0.7,"source_file":"Assets/TextMesh Pro/Sprites/EmojiOne.png"},
  ],
  "input_tokens": 0,
  "output_tokens": 0,
}

# Dedupe nodes by id
seen = set()
deduped = []
for n in combined['nodes']:
    if n['id'] not in seen:
        seen.add(n['id'])
        deduped.append(n)
combined['nodes'] = deduped

Path('.graphify_semantic.json').write_text(json.dumps(combined, indent=2))
print('Wrote .graphify_semantic.json')
print('  nodes:', len(combined['nodes']))
print('  edges:', len(combined['edges']))
print('  hyperedges:', len(combined['hyperedges']))